Repository ProjectBlueHair/FinalProject_BE, pull requests merged in 2023-02, with the labels that each got.

#278 💎 Refactor: Post Domain Facade 패턴 적용
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/requestDto/RequestCreatePostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostServiceFacade.java
Labels: feature, refactor

#280 🐞 BugFix : 채팅방 생성 시 순환참조 문제 해결
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/controller/RoomController.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/service/RoomDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/service/RoomService.java
Labels: bug

#282 ✨ Feat 💎 Refactor 대댓글 알림 기능 추가, NotificationService 메서드 수정
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/controller/NotificationController.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/repository/EmitterRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: feature, refactor

#285 💎 Refactor: my-post 파라미터 변경
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
Labels: refactor

#286 ✨ Feat: 보관함 기능 구현 #281
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/KakaoService.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/entity/Archive.java
  src/main/java/com/bluehair/hanghaefinalproject/post/entity/ArchiveCompositeKey.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/ArchiveRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/JPAArchiveRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#288 ✨ Feat : 채팅방 생성 시 roomId 반환
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/controller/RoomController.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/response/RoomIdDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/service/RoomService.java
Labels: feature

#291 ✨ Feat : 채팅방 생성 시 중복처리
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/repository/RoomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/service/RoomService.java
Labels: feature

#293 ✨ Feat : Message 전송 시 날짜, 시간을 프론트에서 받도록 변경
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/controller/MessageController.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/request/RequestMessageDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/response/ResponseMessageDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/service/MessageDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/service/SaveMessageDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/entity/ChatMessage.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/service/MessageService.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/service/RoomService.java
Labels: feature

#296 🐞 BugFix: 좋아요 여부 확인 로직 수정
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: bug

#297 🐞 BugFix: 좋아요 여부 확인 로직 수정
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: bug

#298 🐞 BugFix: 카카오 계정 마이페이지 데이터 반환 오류
  src/main/java/com/bluehair/hanghaefinalproject/member/service/KakaoService.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
Labels: bug

#294 🐞 BugFix: 메세지 전송이 정상적으로 동작하지 않는 에러 해결
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/controller/MessageController.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/request/RequestMessageDto.java
Labels: bug

#299 🐞 BugFix: 음악 합성 로직 추가
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostServiceFacade.java
Labels: bug

#301 🐞 BugFix: 음원 합성 로직의 Transaction 분리
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostServiceFacade.java
Labels: bug

#302 🐞 BugFix: saveMessageDto -> ChatMessage 변환 로직 수정
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/repository/MessageRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/service/MessageService.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/service/RoomService.java
Labels: bug

#306 ✨ Feat: 버그 리포트 관련 API 구현 #303
  src/main/java/com/bluehair/hanghaefinalproject/bugReport/controller/BugReportController.java
  src/main/java/com/bluehair/hanghaefinalproject/bugReport/dto/BugReportDto.java
  src/main/java/com/bluehair/hanghaefinalproject/bugReport/dto/RequestBugReportDto.java
  src/main/java/com/bluehair/hanghaefinalproject/bugReport/dto/ResponseBugReportDto.java
  src/main/java/com/bluehair/hanghaefinalproject/bugReport/entity/BugReport.java
  src/main/java/com/bluehair/hanghaefinalproject/bugReport/repository/BugReportRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/bugReport/repository/JPABugReportRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/bugReport/service/BugReportService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#307 ✨ Feat : 채팅방 목록 조회 마지막 메세지 반환 추가
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/response/RoomListDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/entity/ChatRoom.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/service/MessageService.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/service/RoomService.java
Labels: feature

#310 ✨ Feat : 채팅방 목록 조회 마지막 메세지 기준으로 최신순 반환
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/repository/RoomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/service/RoomService.java
Labels: feature

#311 🐞 BugFix: 음원 합성 시 클리핑 발생 제거 (리미터 구현)
  src/main/java/com/bluehair/hanghaefinalproject/music/service/AudioEditor.java
Labels: feature

#313 🎬 Publish: 1차 배포 (2023.02.02 21:30)
  src/main/java/com/bluehair/hanghaefinalproject/music/service/AudioSample.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: publish

#315 ✨ Feat: 계정 설정 업데이트 시 계정 닉네임 반환
  src/main/java/com/bluehair/hanghaefinalproject/member/controller/MemberController.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
Labels: feature

#320 ✨ Feat: RefreshToken Redis 적용
  build.gradle
  src/main/java/com/bluehair/hanghaefinalproject/config/RedisConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/RefreshToken.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/RefreshTokenRedisRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/KakaoService.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
Labels: feature

#324 ✨ Feat : Local 환경 Test를 위한 EmbeddedRedis 적용
  build.gradle
  src/main/java/com/bluehair/hanghaefinalproject/config/EmbeddedRedisConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/config/RedisConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/resources/application-h2.properties
  src/main/resources/application.properties
Labels: feature

#322 ✨ Feat Querydsl 적용
  build.gradle
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/repository/CollaboRequestCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/repository/CollaboRequestCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/repository/CollaboRequestRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/config/QuerydslConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/CommentLikeCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/CommentLikeCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/CommentLikeRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/PostLikeCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/PostLikeCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/PostLikeRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostRepository.java
Labels: feature

#325 ✨ Feat: EmbeddedRedis MySQL Test 버전 추가
  .github/workflows/deploy.yml
  .gitignore
  src/main/java/com/bluehair/hanghaefinalproject/config/EmbeddedRedisConfig.java
  src/main/resources/application.properties
Labels: feature

#327 ✨ Feat: Comment, CollaboRequest 도메인 QueryDSL 적용
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/repository/CollaboRequestCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/JPACommentRepository.java
Labels: feature

#329 ✨ Feat: Member, Music Domain QueryDSL 적용
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/Custom/JobCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/Custom/MemberCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/CustomImpl/JobCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/CustomImpl/MemberCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/FollowRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/JPA/JPAFollowRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/JPA/JPAJobRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/JPA/JPAMemberDetailRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/JPA/JPAMemberRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/JobRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/MemberDetailRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/MemberRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
  src/main/java/com/bluehair/hanghaefinalproject/music/repository/JPAMusicRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/music/repository/MusicCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/music/repository/MusicCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/music/repository/MusicRepository.java
Labels: feature

#330 ✨ Feat Post, WebSocket, Tag, CollaboRequest QueryDSL 적용
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/repository/CollaboRequestCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/repository/CollaboRequestCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/repository/CollaboRequestRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/ArchiveCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/ArchiveCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/ArchiveRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/JPAArchiveRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/JPAPostRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/tag/repository/JPATagRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/tag/repository/TagCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/tag/repository/TagCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/tag/repository/TagRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/repository/MessageCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/repository/MessageCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/repository/MessageRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/repository/RoomCustomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/repository/RoomCustomRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/repository/RoomRepository.java
  src/main/resources/application.properties
Labels: feature

#333 ✨ Feat: CDN 적용을 위한 AWS CloudFront URI 적용
  src/main/java/com/bluehair/hanghaefinalproject/music/service/MusicService.java
Labels: feature

#335 🚀 Release: 최종 발표 전 DB 변경 및 정리
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/Member.java
Labels: feature
