Repository ProjectBlueHair/FinalProject_BE, pull requests merged in 2023-01, with the labels that each got.

#20 ✨ Feat: Spring Security 적용
  .gitignore
  build.gradle
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorResponse.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/config/SwaggerConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/member/controller/MemberController.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/TestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/Member.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/MemberRole.java
  src/main/java/com/bluehair/hanghaefinalproject/member/exception/TokenReissuanceExceptionHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/member/mapper/MemberMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
  src/main/java/com/bluehair/hanghaefinalproject/security/CustomUserDetails.java
  src/main/java/com/bluehair/hanghaefinalproject/security/exception/CustomJwtException.java
  src/main/java/com/bluehair/hanghaefinalproject/security/exception/CustomJwtExceptionHandlerFilter.java
  src/main/java/com/bluehair/hanghaefinalproject/security/exception/InvalidMemberException.java
  src/main/java/com/bluehair/hanghaefinalproject/security/exception/InvalidMemberHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/security/jwt/JwtAuthFilter.java
  src/main/java/com/bluehair/hanghaefinalproject/security/jwt/JwtUtil.java
  src/main/java/com/bluehair/hanghaefinalproject/security/service/CustomUserDetailsService.java
  src/main/resources/application.properties
Labels: good first issue, feature

#21 🧪 Test: JwtSecret 적용 오류
  .github/workflows/deploy.yml
Labels: bug

#24 ✨ Feat: Entity 구현
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/entity/CollaboRequest.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/entity/Comment.java
  src/main/java/com/bluehair/hanghaefinalproject/common/entity/Timestamped.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/Member.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/Social.java
  src/main/java/com/bluehair/hanghaefinalproject/music/entity/Music.java
  src/main/java/com/bluehair/hanghaefinalproject/post/entity/Post.java
  src/main/java/com/bluehair/hanghaefinalproject/tag/entity/Tag.java
Labels: good first issue, feature

#29 🐞 BugFix: 인증/인가가 필요하지 않은 페이지에 접근 시 403이 발생하는 현상 수정
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/security/jwt/JwtAuthFilter.java
Labels: bug

#33 ✨ Feat: 회원가입 기능 구현
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorResponse.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SuccessResponse.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/common/service/Validator.java
  src/main/java/com/bluehair/hanghaefinalproject/config/SwaggerConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/member/controller/MemberController.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/MemberDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/RequestLoginMemberDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/RequestSignUpMemberDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/SignUpMemberDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/requestDto/RequestLoginDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/requestDto/RequestSignUpDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/requestDto/RequestValidateEmailDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/requestDto/RequestValidateNicknameDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/serviceDto/LoginDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/serviceDto/SignUpDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/serviceDto/ValidateEmailDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/serviceDto/ValidateNicknameDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/Member.java
  src/main/java/com/bluehair/hanghaefinalproject/member/mapper/MemberMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/MemberRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
  src/main/java/com/bluehair/hanghaefinalproject/security/service/CustomUserDetailsService.java
Labels: feature

#34 ✨ Feat : 게시글 작성 기능 구현
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/RequestPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/entity/Post.java
  src/main/java/com/bluehair/hanghaefinalproject/post/mapper/PostMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/JPAPostRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#37 💎 Refactor : Post 도메인 Service Dto 분리 작업
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/PostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/RequestPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/mapper/PostMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: refactor

#42 ✨ Feat : 게시글 상세 조회 기능 구현
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/requestDto/RequestPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/InfoPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/PostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/exception/NotFoundPostRequestException.java
  src/main/java/com/bluehair/hanghaefinalproject/post/exception/NotFoundPostRequestHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/post/mapper/PostMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#40 ✨ Feat: 사용자 정보 반환 기능 구현
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/member/controller/MemberController.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/responseDto/ResponseMemberInfoDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
Labels: feature

#43 ✨ Feat: 인증/인가 관련 Handler 구현(403 Handling)
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/security/exception/CustomAccessDeniedHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/security/exception/CustomAuthenticationEntryPoint.java
Labels: feature

#47 ✨ Feat : 게시글 전체 조회 기능 구현
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/repository/CollaboRequestRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/music/repository/MusicRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/MainPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/mapper/PostMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#49 ✨ Feat CollaboRequest 상세 조회 API 구현
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestListDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestResponseDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/ResponseCollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/music/dto/ResponseMusicDto.java
  src/main/java/com/bluehair/hanghaefinalproject/music/mapper/MusicMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/music/repository/MusicRepository.java
Labels: feature

#52 🐞 BugFix Merge 시 삭제 된 부분 다시 구현
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/ResponseCollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/ResponseCollaboRequestListDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/music/repository/MusicRepository.java
Labels: bug

#53 🐞 BugFix, ✨ Feat: @Schema 적용 오류 해결 및 Member Domain Swagger 설정
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SuccessResponse.java
  src/main/java/com/bluehair/hanghaefinalproject/config/SwaggerConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/member/controller/MemberController.java
Labels: bug, feature

#55 💎 Refactor: Member Domain Swagger 3 Convention 적용
  src/main/java/com/bluehair/hanghaefinalproject/member/controller/MemberController.java
Labels: refactor

#56 ✨ Feat : 게시글 작성 시 이미지 추가
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/requestDto/RequestPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/PostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/entity/Post.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#58 ✨ Feat 게시글 Collabo Request 전체 조회 구현
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestListDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestListForPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/mapper/CollaboRequestMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/repository/CollaboRequestRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/music/dto/ResponseMusicDto.java
  src/main/java/com/bluehair/hanghaefinalproject/music/repository/MusicRepository.java
Labels: feature

#63 ✨ Feat : 게시글 전체 조회 기능 수정
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/requestDto/RequestPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/InfoPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/MainPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/MainProfileDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/mapper/PostMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#62 💎 Refactor : Post 도메인 Swagger 컨벤션 적용
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/requestDto/RequestPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/InfoPostDto.java
Labels: refactor

#65 ✨ Feat: exceptionhandler 추가
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/InvalidColloboRequestHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
Labels: bug, feature, refactor

#68 ✨ Feat: LocalDateTimeConverter 구현
  src/main/java/com/bluehair/hanghaefinalproject/common/service/LocalDateTimeConverter.java
Labels: feature

#70 ✨ Feat: 팔로우 기능 구현
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/config/SwaggerConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/member/controller/MemberController.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/requestDto/RequestFollowDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/serviceDto/FollowDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/Follow.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/FollowCompositeKey.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/Member.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/FollowRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/JPAFollowRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/JPAMemberRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/MemberRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
Labels: good first issue, feature

#72 ✨ Feat : 게시글 상세 조회 이미지 반환
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/InfoPostDto.java
Labels: feature

#73 ✨ Feat : 게시글 상세조회 조회수증가 추가
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/InfoPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/entity/Post.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#78 💎 Refactor: CollaboRequest 도메인 Swagger 적용
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestListForPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/RequestCollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/ResponseCollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
Labels: refactor

#80 💎 Refactor: 콜라보 리퀘스트 작성 시 musicList로 수정
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/RequestCollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/music/dto/MusicDto.java
  src/main/java/com/bluehair/hanghaefinalproject/music/dto/SaveMusicDto.java
  src/main/java/com/bluehair/hanghaefinalproject/music/mapper/MusicMapStruct.java
Labels: feature, refactor

#79 ✨ Feat : 댓글 작성 기능 구현
  src/main/java/com/bluehair/hanghaefinalproject/comment/controller/CommentController.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/dto/requestDto/RequestCommentDto.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/dto/serviceDto/CommentDto.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/entity/Comment.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/exception/NotFoundCommentRequestException.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/exception/NotFoundCommentRequestHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/mapper/CommentMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/JPACommentRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
Labels: feature

#82 💎 Refactor: approval을 콜라보 리퀘스트 상세 조회시 반환
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/ResponseCollaboRequestDto.java
Labels: feature, refactor

#83 ✨ Feat: 게시물 저장 시 Tag 추출 및 저장
  src/main/java/com/bluehair/hanghaefinalproject/common/service/TagExctractor.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
  src/main/java/com/bluehair/hanghaefinalproject/tag/entity/Tag.java
  src/main/java/com/bluehair/hanghaefinalproject/tag/mapper/TagMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/tag/repository/JPATagRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/tag/repository/TagRepository.java
Labels: feature

#85 ✨ Feat: 콜라보 요청 승인 구현
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/entity/CollaboRequest.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/NotAuthorizedtoApproveException.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/NotAuthorizedtoApproveHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
Labels: feature

#86 ✨ Feat: 승인이 되었을 때만 전체 조회에 불러옴
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
Labels: feature

#89 ✨ Feat 콜라보 리퀘스트 삭제 기능
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/NotAllowedtoDeleteException.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/NotAllowedtoDeleteHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/NotAuthorizedMemberException.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/NotAuthorizedMemberHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/music/repository/MusicRepository.java
Labels: feature

#91 ✨ Feat 콜라보 리퀘스트 수정 기능
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/entity/CollaboRequest.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/mapper/CollaboRequestMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
Labels: feature

#92 ✨ Feat : 댓글 수정
  src/main/java/com/bluehair/hanghaefinalproject/comment/controller/CommentController.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/entity/Comment.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/exception/CommentNotAuthorizedMemberException.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/exception/CommentNotAuthorizedMemberHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
Labels: feature

#94 ✨ Feat: LocalDateTimeConverter 적용
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestListForPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/ResponseCollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/mapper/CollaboRequestMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/common/service/LocalDateTimeConverter.java
Labels: feature

#96 refactor: Custom Exception 컨벤션 변경
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/Domain.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/DuplicationException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/FormatException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/GlobalExceptionHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/InvalidRequestException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/Layer.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/NotAuthorizedMemberException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/NotFoundException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/TokenReissuanceExceptionHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/member/exception/InvalidLoginRequestException.java
  src/main/java/com/bluehair/hanghaefinalproject/member/exception/InvalidLoginRequestHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/member/exception/InvalidSignUpRequestException.java
  src/main/java/com/bluehair/hanghaefinalproject/member/exception/InvalidSignUpRequestHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
Labels: refactor

#103 💎 Refactor: CollaboRequest 도메인 Exception 처리 변경
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/InvalidCollaboRequestException.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/InvalidColloboRequestHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/NotAllowedtoDeleteException.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/NotAllowedtoDeleteHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/NotAuthorizedMemberException.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/NotAuthorizedMemberHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/NotAuthorizedtoApproveException.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/exception/NotAuthorizedtoApproveHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/FormatException.java
Labels: refactor

#101 💎 Refactor: Exception 컨벤션 변경에 따른 Member 도메인 수정
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/FormatException.java
  src/main/java/com/bluehair/hanghaefinalproject/member/controller/MemberController.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
Labels: refactor

#100 💎 Refactor : Post, Comment 도메인 exception 처리 방식 변경
  src/main/java/com/bluehair/hanghaefinalproject/comment/controller/CommentController.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/exception/CommentNotAuthorizedMemberException.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/exception/CommentNotAuthorizedMemberHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/exception/NotFoundCommentRequestException.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/exception/NotFoundCommentRequestHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/MainPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/MainProfileDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/exception/NotFoundPostRequestException.java
  src/main/java/com/bluehair/hanghaefinalproject/post/exception/NotFoundPostRequestHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/post/mapper/PostMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: refactor

#106 ✨ Feat : 댓글 삭제 기능 구현
  src/main/java/com/bluehair/hanghaefinalproject/comment/controller/CommentController.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
Labels: feature

#109 ✨ Feat : 게시글 상세페이지 댓글 조회
  src/main/java/com/bluehair/hanghaefinalproject/comment/controller/CommentController.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/dto/serviceDto/CommentDto.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/dto/serviceDto/CommentListDto.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/entity/Comment.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
Labels: feature

#113 ✨ Feat : 게시글 전체 조회 Profile 중복 제거
  src/main/java/com/bluehair/hanghaefinalproject/music/repository/MusicRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/MainPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/MainProfileDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/mapper/PostMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#114 ✨ Feat: SSE 연결, 콜라보 승인시 콜라보 작성자에게 알림 전송
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/Domain.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/controller/NotificationController.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/dto/ResponseNotificationDto.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/entity/Notification.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/entity/NotificationContent.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/entity/NotificationType.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/entity/RelatedUrl.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/mapper/SseMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/repository/EmitterRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/repository/EmitterRepositoryImpl.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/repository/NotificationRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: feature

#116 ✨ Feat: Music Domain 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/RequestCollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/common/service/MultipartFileConverter.java
  src/main/java/com/bluehair/hanghaefinalproject/config/AwsConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/music/dto/MusicDto.java
  src/main/java/com/bluehair/hanghaefinalproject/music/dto/SaveMusicDto.java
  src/main/java/com/bluehair/hanghaefinalproject/music/mapper/MusicMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/AudioEditor.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/AudioSample.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/MusicService.java
  src/main/java/com/bluehair/hanghaefinalproject/post/entity/Post.java
  src/main/resources/application.properties
Labels: feature

#121 ✨ Feat : CommentListDto에 댓글 id 추가
  src/main/java/com/bluehair/hanghaefinalproject/comment/dto/serviceDto/CommentListDto.java
Labels: feature

#124 ✨ Feat: 게시글 전체 콜라보리스트 조회 시 음원 리스트 함께 반환
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestListForPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/mapper/CollaboRequestMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
Labels: feature

#118 ✨ Feat 콜라보 요청시 post 작성자에게 알림 전송
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/entity/Notification.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: feature, refactor

#128 ✨ Feat 댓글 작성시 게시글 작성자에게 알림 전송
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
Labels: bug, feature

#129 ✨ Feat : 게시글 전체 조회 시 이미지와 태그리스트 추가 반환
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/MainPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/mapper/PostMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
  src/main/java/com/bluehair/hanghaefinalproject/tag/repository/TagRepository.java
Labels: feature

#133 ✨ Feat 게시글 좋아요/취소
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/post/entity/Post.java
  src/main/java/com/bluehair/hanghaefinalproject/postLike/controller/PostLikeController.java
  src/main/java/com/bluehair/hanghaefinalproject/postLike/dto/ResponsePostLikeDto.java
  src/main/java/com/bluehair/hanghaefinalproject/postLike/entity/PostLike.java
  src/main/java/com/bluehair/hanghaefinalproject/postLike/entity/PostLikeCompositeKey.java
  src/main/java/com/bluehair/hanghaefinalproject/postLike/repository/JPAPostLikeRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/postLike/repository/PostLikeRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/postLike/service/PostLikeService.java
Labels: feature

#135 ✨ Feat 댓글 좋아요, 게시글 좋아요 시 알림 전송
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/postLike/service/PostLikeService.java
Labels: feature

#139 ✨ Feat: 프로젝트 RDS MySQL 적용
  .gitignore
  build.gradle
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/resources/application.properties
Labels: feature

#141 💎 Refactor Like 도메인 생성 및 관련 기능 이동
  src/main/java/com/bluehair/hanghaefinalproject/comment/controller/CommentController.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/like/controller/LikeController.java
  src/main/java/com/bluehair/hanghaefinalproject/like/dto/ResponsePostLikeDto.java
  src/main/java/com/bluehair/hanghaefinalproject/like/entity/CommentLike.java
  src/main/java/com/bluehair/hanghaefinalproject/like/entity/CommentLikeCompositeKey.java
  src/main/java/com/bluehair/hanghaefinalproject/like/entity/PostLike.java
  src/main/java/com/bluehair/hanghaefinalproject/like/entity/PostLikeCompositeKey.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/CommentLikeRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/JPACommentLikeRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/JPAPostLikeRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/PostLikeRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/like/service/LikeService.java
  src/main/java/com/bluehair/hanghaefinalproject/postLike/controller/PostLikeController.java
  src/main/java/com/bluehair/hanghaefinalproject/postLike/service/PostLikeService.java
Labels: refactor

#142 💎 Refactor: Music, CollaboRequest Domain Refactoring
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestDetailsDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestListForPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/RequestCollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/ResponseCollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/entity/CollaboRequest.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/mapper/CollaboRequestMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/GlobalExceptionHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/InvalidAudioFileException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/service/Validator.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/MusicService.java
Labels: refactor

#143 🐞 BugFix: Post에 작성된 CollaboRequest가 없을 시, 제외하고 합성하는 로직 추가
  src/main/java/com/bluehair/hanghaefinalproject/music/service/MusicService.java
Labels: bug

#140 ✨ Feat : 댓글 리스트 반환 로직 변경
  src/main/java/com/bluehair/hanghaefinalproject/comment/dto/serviceDto/CommentListDto.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/dto/serviceDto/ReplyDto.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
Labels: feature

#145 ✨ Feat: 게시글 상세 조회 시 음악 리스트 반환 API 구현 #144
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestListForPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/mapper/CollaboRequestMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/music/dto/ResponseMusicDto.java
  src/main/java/com/bluehair/hanghaefinalproject/music/mapper/MusicMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#147 ✨ Feat: 토큰 관련 에러 발생 시, 401로 반환
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
Labels: feature

#149 ✨ Feat: AccessToken 유효시간 수정
  src/main/java/com/bluehair/hanghaefinalproject/security/jwt/JwtUtil.java
Labels: feature

#151 🐞 BugFix: AccessToken 재발급 API Security 예외처리
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/security/exception/CustomJwtExceptionHandlerFilter.java
  src/main/java/com/bluehair/hanghaefinalproject/security/jwt/JwtAuthFilter.java
Labels: bug

#154 ✨ Feat: 게시글 작성 및 콜라보 리퀘스트 작성 시 ID 반환
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/MusicService.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#156 ✨ Feat: 게시글 상세 조회 시 작성 시간, 태그 리스트 반환
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestDetailsDto.java
  src/main/java/com/bluehair/hanghaefinalproject/common/service/LocalDateTimeConverter.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/InfoPostDto.java
Labels: feature

#163 ✨ Feat : 게시글 검색
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#158 ✨ Feat 콜라보 전체 조회시 콜라보 작성자 팔로우 정보 반환
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestListForPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/mapper/CollaboRequestMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
Labels: feature

#160 💎 Refactor 게시글 상세 조회시 isLiked 반환
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/InfoPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: refactor

#162 ✨ Feat: Audio Sample 파일 관련 에러 처리 #161
  src/main/java/com/bluehair/hanghaefinalproject/common/service/Validator.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/AudioSample.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/MusicService.java
Labels: feature

#165 🐞 BugFix : url이 겹치는 문제 해결
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
Labels: bug

#170 ✨ Feat: 콜라보 목록 조회시, contents 함께 반환
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/CollaboRequestListForPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/mapper/CollaboRequestMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/AudioSample.java
Labels: feature

#173 ✨ Feat: 댓글 좋아요 여부 및 좋아요 수 반환
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/like/controller/LikeController.java
  src/main/java/com/bluehair/hanghaefinalproject/like/dto/CommentLikeDto.java
  src/main/java/com/bluehair/hanghaefinalproject/like/dto/PostLikeDto.java
  src/main/java/com/bluehair/hanghaefinalproject/like/service/LikeService.java
Labels: feature, refactor

#175 ✨ Feat : 작성한 게시글 조회
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#177 ✨ Feat : 댓글, 대댓글 좋아요 갯수, 좋아요 여부 반환 추가
  src/main/java/com/bluehair/hanghaefinalproject/comment/controller/CommentController.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/dto/serviceDto/CommentListDto.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/dto/serviceDto/ReplyDto.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
Labels: feature

#182 💎 Refactor : 게시글 작성 시 contents컬럼이 null을 허용합니다.
  src/main/java/com/bluehair/hanghaefinalproject/post/entity/Post.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: refactor

#183 💎 Refactor: lyrics를 collaboNotice로 수정
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/requestDto/RequestPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/requestDto/RequestUpdatePostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/InfoPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/PostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/PostUpdateDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/entity/Post.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: refactor

#187 🐞 BugFix: FE 요청에 따른 서버 CORS 설정 수정
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
Labels: bug

#189 ✨ Feat: FE 요청에 따른 토큰 관련 에러 응답 수정
  src/main/java/com/bluehair/hanghaefinalproject/common/response/error/ErrorCode.java
Labels: feature

#191 🐞 BugFix: postDto에서 contents에서 Tag를 추출할 시, 없을 경우 null 관련 처리가 안되는 경우 처리
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: bug

#192 ✨ Feat : 댓글 삭제 시 해당 댓글에 담긴 좋아요도 삭제되도록 변경
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/CommentLikeRepository.java
Labels: feature

#198 💎 Refactor ✨ Feat 알림 전송 시 발신자 정보 및 리디렉션 정보 추가, 최신순으로 알림 목록 조회
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/like/service/LikeService.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/dto/ResponseNotificationDto.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/entity/Notification.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/entity/RedirectionType.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/entity/RelatedUrl.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/entity/Sender.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/repository/NotificationRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: feature, refactor

#194 ✨ Feat: CollaboRequest 상세 조회 시, PostId 함께 반환
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/ResponseCollaboRequestDto.java
Labels: feature

#201 ✨ Feat 콜라보 알림 전송 시 해당 Post Id 정보 추가
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/like/service/LikeService.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/dto/ResponseNotificationDto.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/entity/Notification.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/entity/RelatedUrl.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: feature

#205 ✨ Feat : 게시글 삭제
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/repository/CollaboRequestRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/CommentLikeRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/PostLikeRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
  src/main/java/com/bluehair/hanghaefinalproject/tag/repository/TagRepository.java
Labels: feature

#202 ✨ Feat: 오디오 파일 형식 관련 예외 발생 시, Post 삭제 기능 구현
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/GlobalExceptionHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/InvalidAudioFileException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/service/MultipartFileConverter.java
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/AudioSample.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/MusicService.java
Labels: feature

#208 🐞 BugFix 게시글 좋아요 비관적 락 추가
  src/main/java/com/bluehair/hanghaefinalproject/like/repository/PostLikeRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/like/service/LikeService.java
  src/main/java/com/bluehair/hanghaefinalproject/post/entity/Post.java
Labels: bug

#212 ✨ Feat 알림 발신자와 수신자가 같으면 알림을 미발신
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/like/service/LikeService.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#214 ✨ Feat : 게시글 전체 조회시 좋아요 여부 반환
  src/main/java/com/bluehair/hanghaefinalproject/post/controller/PostController.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/serviceDto/MainPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/mapper/PostMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: feature

#210 ✨ Feat: 게시글 작성 시 작성되는 첫 CollaboRequest 생성 API 추가
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/MusicService.java
  src/main/resources/application.properties
Labels: feature

#216 💎 Refactor: 알림 구독 시 멤버 정보를 nickname으로 가져옴
  src/main/java/com/bluehair/hanghaefinalproject/sse/controller/NotificationController.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: refactor

#218 ✨ Feat: Spring Security SSE Subscribe API 예외설정
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
Labels: feature

#220 ✨ Feat: SSE Connection Pool Error 확인을 위한 Debug Option 추가
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/controller/NotificationController.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
  src/main/resources/application.properties
Labels: feature

#225 💎 Refactor: Exception Convention 변경
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/DuplicationException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/FormatException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/GlobalExceptionHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/InvalidAudioFileException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/InvalidRequestException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/NotAuthorizedMemberException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/NotFoundException.java
  src/main/java/com/bluehair/hanghaefinalproject/common/service/MultipartFileConverter.java
  src/main/java/com/bluehair/hanghaefinalproject/like/service/LikeService.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/AudioSample.java
  src/main/java/com/bluehair/hanghaefinalproject/music/service/MusicService.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
  src/test/java/com/bluehair/hanghaefinalproject/member/service/MemberServiceTest.java
Labels: refactor

#227 🐞 BugFix: 비동기처리를 위해 @Async 추가
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: bug

#228 💎 Refactor: DTO, Entity, Mapper 적용 현황 확인 및 개선
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/controller/CollaboRequestController.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/requestDto/RequestCollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/responseDto/ResponseCollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/responseDto/ResponseCollaboRequestListForPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/serviceDto/CollaboRequestDetailsDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/dto/serviceDto/CollaboRequestDto.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/entity/CollaboRequest.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/mapper/CollaboRequestMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/dto/serviceDto/CommentListDto.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/dto/serviceDto/ReplyDto.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/entity/Comment.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/mapper/CommentMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/common/service/TagExctractor.java
  src/main/java/com/bluehair/hanghaefinalproject/member/mapper/MemberMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
  src/main/java/com/bluehair/hanghaefinalproject/music/entity/Music.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/responseDto/ResponseInfoPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/dto/responseDto/ResponseMainPostDto.java
  src/main/java/com/bluehair/hanghaefinalproject/post/mapper/PostMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: help wanted, refactor

#229 ✨ Feat 읽지않은알림 갯수 세기
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/controller/NotificationController.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/dto/ResponseCountNotificationDto.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/repository/NotificationRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: feature

#230 🐞 BugFix SSE 오류 관련
  src/main/java/com/bluehair/hanghaefinalproject/HanghaeFinalProjectApplication.java
  src/main/java/com/bluehair/hanghaefinalproject/like/service/LikeService.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: bug

#233 ✨ Feat: 계정 설정 업데이트 및 조회 API 작성
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/member/controller/MemberController.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/requestDto/RequestSettingDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/responseDto/ResponseSettingDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/serviceDto/SettingMemberDetailDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/serviceDto/SettingMemberDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/Job.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/Member.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/MemberDetail.java
  src/main/java/com/bluehair/hanghaefinalproject/member/mapper/MemberMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/JPA/JPAFollowRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/JPA/JPAJobRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/JPA/JPAMemberDetailRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/JPA/JPAMemberRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/JobRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/MemberDetailRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
Labels: feature

#235 ✨ Feat: FE 신규 페이지 CORS 설정
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
Labels: feature

#236 ✨ Feat EventListener 적용하여 NotificationService 의존성 제거
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/service/CollaboRequestService.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/service/CommentService.java
  src/main/java/com/bluehair/hanghaefinalproject/like/service/LikeService.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/dto/RequestNotificationDto.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/listener/NotificationListener.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: feature, refactor

#238 ✨ Feat: 마이페이지 유저정보 반환 API
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/member/controller/MemberController.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/responseDto/ResponseMypageDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/mapper/MemberMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
Labels: feature

#239 ✨ Feat : 채팅 기능 추가
  build.gradle
  src/main/java/com/bluehair/hanghaefinalproject/common/exception/Domain.java
  src/main/java/com/bluehair/hanghaefinalproject/common/response/success/SucessCode.java
  src/main/java/com/bluehair/hanghaefinalproject/member/repository/MemberRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/config/ChatConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/config/ChatHandler.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/controller/MessageController.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/controller/RoomController.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/request/RequestMessageDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/response/MessageListDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/response/RoomListDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/service/MessageDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/service/RoomDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/dto/service/SaveMessageDto.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/entity/ChatMessage.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/entity/ChatRoom.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/mapper/MessageMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/mapper/RoomMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/repository/MessageRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/repository/RoomRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/service/MessageService.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/service/RoomService.java
Labels: feature

#241 💎 Refactor: MemberDetail의 SNS 활성화 여부 false로 초기 설정 #240
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/MemberDetail.java
Labels: refactor

#243 🐞 BugFix: compositekey 값 수정
  src/main/java/com/bluehair/hanghaefinalproject/post/service/PostService.java
Labels: bug

#245 ✨ Feat: MemberDetail SNS URL 기본 값 지정
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/MemberDetail.java
Labels: feature

#248 💎 Refactor : RoomController 오타 수정
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/controller/RoomController.java
Labels: refactor

#249 🐞 BugFix: media 타입 추가
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: bug

#250 🐞 BugFix: gson 사용하여 객체 직렬
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: bug

#253 🐞 BugFix: 계정 설정 시, AccessToken 만료 Status Code 전송
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
Labels: bug

#254 💎 Refactor data에 notification 대신 String 타입인 notificationContent를 전송
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: refactor

#256 🐞 BugFix: 회원 정보(nickname) 변경 시 변경 내역이 DB에 적용되지 않는 문제 수정
  src/main/java/com/bluehair/hanghaefinalproject/collaboRequest/repository/CollaboRequestRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/CommentRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/comment/repository/JPACommentRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/JPAPostRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/post/repository/PostRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/repository/NotificationRepository.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/repository/MessageRepository.java
Labels: bug

#258 ✨ Feat:채팅 관련 authorizeRequests 추가
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
Labels: feature

#260 🐞 BugFix: produce하는 context-type의 라이브러리 변경
  src/main/java/com/bluehair/hanghaefinalproject/sse/controller/NotificationController.java
Labels: bug

#259 🐞 BugFix: Embeded Type Sender 변경에서 Sender.sender로 변경
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/MemberDetail.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/repository/NotificationRepository.java
Labels: bug

#264 💎 Refactor: nickname으로 멤버값 불러 오는 것으로 변경
  src/main/java/com/bluehair/hanghaefinalproject/sse/controller/NotificationController.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: refactor

#265 ✨ Feat: Kakao Social Login 기능 구현 #263
  .gitignore
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/member/controller/MemberController.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/serviceDto/KakaoLoginDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/entity/Member.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/KakaoService.java
Labels: feature

#262 🐞 BugFix : room 도메인 404 에러 픽스
  src/main/java/com/bluehair/hanghaefinalproject/config/WebSecurityConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/controller/MessageController.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/controller/RoomController.java
Labels: bug

#266 🐞 BugFix: SSE 관련 Header 추가
  src/main/java/com/bluehair/hanghaefinalproject/sse/config/AsyncConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/controller/NotificationController.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
  src/main/resources/application.properties
Labels: bug

#268 🐞 BugFix : 커넥션 생성이 되지 않는 에러 해결
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/config/ChatConfig.java
  src/main/java/com/bluehair/hanghaefinalproject/webSocket/controller/MessageController.java
Labels: bug

#271 🐞 BugFix: 카카오 소셜 로그인 500 Error 처리
  src/main/java/com/bluehair/hanghaefinalproject/member/service/KakaoService.java
Labels: bug

#273 🐞 BugFix: complete 삭제
  src/main/java/com/bluehair/hanghaefinalproject/sse/listener/NotificationListener.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/service/NotificationService.java
Labels: bug

#275 ✨ Feat: 마이페이지 팔로우 여부 반환
  src/main/java/com/bluehair/hanghaefinalproject/member/controller/MemberController.java
  src/main/java/com/bluehair/hanghaefinalproject/member/dto/responseDto/ResponseMypageDto.java
  src/main/java/com/bluehair/hanghaefinalproject/member/mapper/MemberMapStruct.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/KakaoService.java
  src/main/java/com/bluehair/hanghaefinalproject/member/service/MemberService.java
  src/main/java/com/bluehair/hanghaefinalproject/security/jwt/JwtUtil.java
  src/main/java/com/bluehair/hanghaefinalproject/sse/controller/NotificationController.java
Labels: feature
